name: ci-server

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'server/**'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'server/**'

jobs:
  sonarqube:
    permissions:
      contents: read
      pull-requests: write
    name: SonarQube
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'
      - name: Install SonarQube Tools
        run: |
          dotnet tool install -g dotnet-sonarscanner
          dotnet tool install -g dotnet-reportgenerator-globaltool
      - name: Start Static Code Analysis
        run: |
          dotnet sonarscanner begin \
            /k:"IncidentTracker" \
            /d:sonar.host.url=${{ secrets.SONAR_HOST_URL }} \
            /d:sonar.token=${{ secrets.SONAR_TOKEN }} \
            /d:sonar.coverageReportPaths="coverage-report/SonarQube.xml" \
            /d:sonar.qualitygate.wait=true \
            /d:sonar.qualitygate.timeout=300
          
  build:
    permissions:
      contents: read
      pull-requests: write
    name: Build Server
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server

    needs: sonarqube

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - run: dotnet restore
      - run: dotnet build -c Release --no-restore

  test:
    permissions:
      contents: read
      pull-requests: write
    name: Test Server
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server

    needs: build

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - run: dotnet restore
      - run: dotnet test -c Release /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:CoverletOutput=TestResults/coverage.xml
      - name: List TestResults directory for debug
        run: |
          echo "Listing TestResults contents:"
          ls -l TestResults || true
      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: TestResults/coverage.xml
  
  report:
    permissions:
      contents: read
      pull-requests: write
    name: Report Server Coverage
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server

    needs: test

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Download coverage
        uses: actions/download-artifact@v4
        with:
          name: coverage
          path: TestResults

      - name: Install ReportGenerator
        run: dotnet tool install -g dotnet-reportgenerator-globaltool
      - name: Generate coverage report
        run: |
          reportgenerator \
          -reports:TestResults/coverage.xml \
          -targetdir:coverage-report \
          -reporttypes:SonarQube

  completeAnalysis:
    permissions:
      contents: read
      pull-requests: write
    name: Complete Analysis
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server

    needs: report

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'
          
      - name: Complete Static Code Analysis
        run: |
          dotnet sonarscanner end /d:sonar.token=${{ secrets.SONAR_TOKEN }}